apiVersion: 1

datasources:
  - name: iot_postgres
    uid: iot_postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${PIPELINE_DB_USER}
    secureJsonData:
      password: ${PIPELINE_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true

  - name: loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true

  - name: airflow_postgres
    uid: airflow_postgres
    type: postgres
    access: proxy
    url: airflow-postgres:5432
    database: ${AIRFLOW_DB_NAME}
    user: ${GRAFANA_AIRFLOW_DB_USER}
    secureJsonData:
      password: ${GRAFANA_AIRFLOW_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    editable: true
